UPDATE `taxon_group` SET `description` = 'mosdiertjes', `icon` = 'animals' WHERE `code` LIKE 'BRHYP';
UPDATE `taxon_group` SET `description` = 'dansmuggen', `icon` = 'mosquito' WHERE `code` LIKE 'IDCHI';
UPDATE `taxon_group` SET `description` = 'vlokreeften', `icon` = 'shrimp' WHERE `code` LIKE 'CRAMP';
UPDATE `taxon_group` SET `description` = 'tweekleppigen', `icon` = 'big-mussel' WHERE `code` LIKE 'MOBIV';
UPDATE `taxon_group` SET `description` = 'borstelwormen', `icon` = 'earth-worm' WHERE `code` LIKE 'APPOL';
UPDATE `taxon_group` SET `description` = 'slakken', `icon` = 'snail' WHERE `code` LIKE 'MOGAS';
UPDATE `taxon_group` SET `description` = 'vlinders', `icon` = 'butterfly-1' WHERE `code` LIKE 'INLEP';
UPDATE `taxon_group` SET `description` = 'mijten', `icon` = 'mite' WHERE `code` LIKE 'ARACH';
UPDATE `taxon_group` SET `description` = 'ringwormen', `icon` = 'worm-facing-left' WHERE `code` LIKE 'APOLI';
UPDATE `taxon_group` SET `description` = 'kreeften en garnalen', `icon` = 'lobster' WHERE `code` LIKE 'CRDEC';
UPDATE `taxon_group` SET `description` = 'kevers', `icon` = 'chrysomela' WHERE `code` LIKE 'INCOL';
UPDATE `taxon_group` SET `description` = 'steenvliegen', `icon` = 'fly' WHERE `code` LIKE 'INREM';
UPDATE `taxon_group` SET `description` = 'overige vliegen en muggen', `icon` = 'hoverfly' WHERE `code` LIKE 'IDREM';
UPDATE `taxon_group` SET `description` = 'schietmotten', `icon` = 'butterfly' WHERE `code` LIKE 'INTRI';
UPDATE `taxon_group` SET `description` = 'libellen', `icon` = 'dragonfly' WHERE `code` LIKE 'INODO';
UPDATE `taxon_group` SET `description` = 'bloedzuigers', `icon` = 'worm-outline-inside-a-circle' WHERE `code` LIKE 'APHIR';
UPDATE `taxon_group` SET `description` = 'haften', `icon` = 'dragonfly-hand-drawn-insect' WHERE `code` LIKE 'INEPH';
UPDATE `taxon_group` SET `description` = 'pissebedden', `icon` = 'insects' WHERE `code` LIKE 'CRISO';
UPDATE `taxon_group` SET `description` = 'wantsen', `icon` = 'bug' WHERE `code` LIKE 'INHET';
UPDATE `taxon_group` SET `description` = 'platwormen', `icon` = 'earthworm-shape' WHERE `code` LIKE 'APTUR';
UPDATE `taxon_group` SET `description` = 'kriebelmuggen', `icon` = 'mosquito-4' WHERE `code` LIKE 'IDSIM';
UPDATE `taxon_group` SET `description` = 'aasgarnalen', `icon` = 'big-shrimp' WHERE `code` LIKE 'CRMYS';
